### ISSUE TITLE
HHPresentStyleCircle模式 动画没播放完锁屏会卡死

### ISSUE THREAD

**Issue by lidian6864677** [yuwind/HHTransition#15]
HHPresentStyleCircle模式 动画没播放完锁屏会卡死，
我更改了transitionDuration的时间 之后操作是必现的。

**Comment by yuwind** [comment]
已解决，原因是在动画未完成时代理回调为NO，导致转场无法结束，现已修改
`- (void)animationDidStop:(CAAnimation *)anim finished:(BOOL)flag {
    [self.transitionContext completeTransition:YES];
    [self.shapeLayer removeAllAnimations];
}`

**Comment by lidian6864677** [comment]
收到 感谢



在 2020-09-30 11:45:53，"yufeng" <notifications@github.com> 写道：

已解决，原因是在动画未完成时代理回调为NO，导致转场无法结束，现已修改
- (void)animationDidStop:(CAAnimation *)anim finished:(BOOL)flag { [self.transitionContext completeTransition:YES]; [self.shapeLayer removeAllAnimations]; }
