### ISSUE TITLE
可以做到push新界面时和返回有一样的效果吗

### ISSUE THREAD

**Issue by feng562925462** [yuwind/HHTransition#2]
我想做的效果是右滑返回和左滑进入新界面效果基本一致，不知道是不支持还是我没找到对应的处理方法

**Comment by feng562925462** [comment]
present如何实现CATransition3D 能不能给举个🌰，麻烦啦，

**Comment by yuwind** [comment]
在AnimationErectBegin.m里面有动画，你可以看下
