### ISSUE TITLE
一个崩溃问题

### ISSUE THREAD

**Issue by X-man-rascal** [yuwind/HHTransition#20]
自定义转场push之后再正常present一个VC，在VC里dismiss会崩溃
Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'preferredInterfaceOrientationForPresentation 'unknown' must match a supported interface orientation: 'portrait'!'
这个如何解决？谢谢

**Comment by yuwind** [comment]
unknown改下
![image](https://user-images.githubusercontent.com/16901415/137054497-4b3f9768-8b6e-4601-9f65-a946fcf0e9a0.png)

**Comment by X-man-rascal** [comment]
> UIInterfaceOrientationUnknown改为UIInterfaceOrientationPortrait 或者拉下最新的代码

好的我尝试拉下新代码 还是会崩溃（modalPresentationStyle = UIModalPresentationFullScreen） 设置UIInterfaceOrientationPortrait是哪里设置呀
