### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by CoderTingfeng** [yuwind/HHTransition#3]
假如vc1 push到vc2用样式一   然后vc2 push到vc3用样式二，这时候vc2 pop 回vc1是样式二而不是样式一

**Comment by yuwind** [comment]
谢谢你的提醒，这个bug很好，确实存在这个bug，是由于代理绑定在了navgation上，造成后者会覆盖掉前者的代理，改进是把枚举类型绑定在跳转的控制器上，现在已经解决了，你在clone下试试吧。
