### ISSUE TITLE
可以控制动画时间吗

### ISSUE THREAD

**Issue by iosKey** [yuwind/HHTransition#5]
在工程里面push太快了 动画一闪而过 看不清楚 能慢一点就好了

**Comment by yuwind** [comment]
你好，这个暂时没提供修改动画时间，默认是0.3s，如果需要可以这样修改，
找到你要修改的动画类
1、- (NSTimeInterval)transitionDuration:(id<UIViewControllerContextTransitioning>)transitionContext
修改这个返回时间
2、如果这个函数（- (void)animateTransition:(id<UIViewControllerContextTransitioning>)transitionContext）有动画，也需要修改下时间，希望能帮到你。

**Comment by iosKey** [comment]
还有一个问题 你这个库 pod install 根本找不到哦

**Comment by yuwind** [comment]
我理解你说的了，你说的应该是后面几个我用的CATransition做的转场动画，这个是对layer层做转场，交互pop时没有动画，这个暂时还解决不了。如果你有好的注意也可以通知我下。那个pod是可以安装的，这是我刚试的，你再试下吧。
-> HHTransition (1.2.0)
   Transition
   pod 'HHTransition', '~> 1.2.0'
   - Homepage: https://github.com/yuwind/HHTransition/wiki
   - Source:   https://github.com/yuwind/HHTransition.git
   - Versions: 1.2.0, 1.0.0 [master repo]
(END)
