### ISSUE TITLE
使用这个框架实现从底部弹出效果以后，从弹出的controller点击按钮在跳转到下一个界面，这时下一个界面返回的时候会出现弹出的controller会填满整个屏幕，这个问题怎么解决？

### ISSUE THREAD

**Issue by 951501195** [yuwind/HHTransition#8]
使用这个框架实现从底部弹出效果以后，从弹出的controller点击按钮在跳转到下一个界面，这时下一个界面返回的时候会出现弹出的controller会填满整个屏幕，这个问题怎么解决？

**Comment by yuwind** [comment]
这个一般只作为消息选择，如果要跳页面，这个需要做处理，1，使用视图做动画，这样就可以脱离控制器的限制，因为在dismiss的时候containerView会重新布局，而且那个容器我们拿不到，视图动画代码如下：
- (void)showFoldAnimalWithBgView:(UIView *)bgView CoverView:(UIView *)coverView height:(CGFloat)height
{
    if (coverView.frame.origin.y == height) {
        [self hideFoldAnimalWithCoverView:coverView];
        return;
    }
    bgView.userInteractionEnabled = NO;
    coverView.frame = CGRectMake(0, [UIScreen mainScreen].bounds.size.height, [UIScreen mainScreen].bounds.size.width, height);
    self.layer.frame = CGRectMake(0, [UIScreen mainScreen].bounds.size.height/2, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height);
    self.layer.anchorPoint = CGPointMake(0.5, 1);
    
    CATransform3D rotate = CATransform3DIdentity;
    rotate.m34 = -1.0 / 1000;
    rotate = CATransform3DRotate(rotate, 2.5 * M_PI/180.0, 1, 0, 0);
    
    CATransform3D scale = CATransform3DIdentity;
    scale = CATransform3DScale(scale, 0.95, 0.97, 1);
    [UIView animateWithDuration:FoldAnimalTime animations:^{
        
        self.layer.transform = rotate;
        self.alpha = 0.8;
    }completion:^(BOOL finished) {
        [UIView animateWithDuration:FoldAnimalTime animations:^{
            
            self.layer.transform = scale;
            self.alpha = 0.5;
        }];
    }];
    
    [UIView animateWithDuration:FoldAnimalTime*2 animations:^{
        CGRect tempFrame = coverView.frame;
        tempFrame.origin.y = [UIScreen mainScreen].bounds.size.height - height;
        coverView.frame = tempFrame;
    }completion:^(BOOL finished) {
        bgView.userInteractionEnabled = YES;
    }];
}
- (void)hideFoldAnimalWithCoverView:(UIView *)coverView
{
    coverView.layer.zPosition = MAXFLOAT;
    CATransform3D rotate = CATransform3DIdentity;
    rotate.m34 = -1.0 / 1000.0;
    rotate = CATransform3DRotate(rotate, 4.0 * M_PI/180.0, 1, 0, 0);
    
    CATransform3D scale = CATransform3DIdentity;
    scale = CATransform3DTranslate(rotate, 0, -5, 0);
    
    [UIView animateWithDuration:FoldAnimalTime animations:^{
        self.layer.transform = scale;
        self.alpha = .8;
    }completion:^(BOOL finished) {
        [UIView animateWithDuration:FoldAnimalTime animations:^{
            self.layer.transform = CATransform3DIdentity;
            self.alpha = 1;
        }completion:^(BOOL finished) {
            self.layer.anchorPoint = CGPointMake(0.5, 0.5);
            self.layer.frame = CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height);
            
        }];
    }];
    
    [UIView animateWithDuration:FoldAnimalTime*2 animations:^{
        CGRect tempFrame = coverView.frame;
        tempFrame.origin.y = [UIScreen mainScreen].bounds.size.height;
        coverView.frame = tempFrame;
    } completion:^(BOOL finished) {
        [coverView.superview removeFromSuperview];
    }];
}
2、额外加些限制，在跳转之前，传给下级页面当前页面正常的frame
nextVC.complete = ^{
        CGRect frame = self.view.frame;
        frame.origin.y = [UIScreen mainScreen].bounds.size.height - 400;
        self.view.frame = frame;
        self.view.layer.zPosition = MAXFLOAT;
    };
    self.view.layer.zPosition = 0;
在下一页面销毁的时候调动这个complete()，也可以实现。
[self dismissViewControllerAnimated:NO completion:self.complete];动画设置为NO以免会产生向下移动的效果。

**Comment by yuwind** [comment]
已解决，绑定代理为当前控制器，前面弹窗由用户控制。
